Repository java-practice-spb-2020/epam-ifmo-java-practice-2020-1, pull requests merged in 2020-02, with the labels that each got.

#22 Issue #21 extend project structure
  src/main/java/com/ifmo/epampractice/controller/MainServlet.java
  src/main/java/com/ifmo/epampractice/entity/Answers.java
  src/main/java/com/ifmo/epampractice/entity/Attempts.java
  src/main/java/com/ifmo/epampractice/entity/Groups.java
  src/main/java/com/ifmo/epampractice/entity/Questions.java
  src/main/java/com/ifmo/epampractice/entity/Subjects.java
  src/main/java/com/ifmo/epampractice/entity/Tests.java
  src/main/java/com/ifmo/epampractice/entity/Users.java
  src/main/java/com/ifmo/epampractice/service/DatabaseSource.java
  src/main/java/com/ifmo/epampractice/service/IDAO.java
  src/main/java/com/ifmo/epampractice/servlets/MainServlet.java
Labels: enhancement

#40 Issue #30 Properties
  src/main/java/com/ifmo/epampractice/service/PropertiesService.java
  src/main/resources/properties/database.properties
Labels: enhancement

#48 Issue #47 Reconfigure postgresql driver version in build.gradle #47
  build.gradle
Labels: bug

#49 Issue 23 Add c3p0 lib & Setting up connection pool
  build.gradle
  src/main/java/com/ifmo/epampractice/controller/MainServlet.java
  src/main/java/com/ifmo/epampractice/service/DatabaseSource.java
  src/main/resources/properties/database.properties
Labels: enhancement

#63 Issue #62 Change the returned object
  src/main/java/com/ifmo/epampractice/service/DatabaseSource.java
Labels: bug

#65 Issue #25 Add UsersDAO & Users entity
  src/main/java/com/ifmo/epampractice/dao/UsersDAO.java
  src/main/java/com/ifmo/epampractice/entity/Users.java
  src/main/java/com/ifmo/epampractice/enums/Roles.java
Labels: enhancement

#88 Fix all tests
  src/main/java/com/ifmo/epampractice/dao/AnswersDAO.java
  src/main/java/com/ifmo/epampractice/dao/AttemptsDAO.java
  src/main/java/com/ifmo/epampractice/dao/GroupsDAO.java
  src/main/java/com/ifmo/epampractice/dao/QuestionsDAO.java
  src/main/java/com/ifmo/epampractice/dao/SubjectsDAO.java
  src/main/java/com/ifmo/epampractice/dao/TestsDAO.java
  src/main/java/com/ifmo/epampractice/utilities/TestUtilities.java
  src/main/resources/Database_script_test.sql
  src/test/java/com/ifmo/epampractice/dao/AnswersDAOTest.java
  src/test/java/com/ifmo/epampractice/dao/AttemptsDAOTest.java
  src/test/java/com/ifmo/epampractice/dao/GroupsDAOTest.java
  src/test/java/com/ifmo/epampractice/dao/QuestionsDAOTest.java
  src/test/java/com/ifmo/epampractice/dao/SubjectsDAOTest.java
  src/test/java/com/ifmo/epampractice/dao/TestsDAOTest.java
  src/test/java/com/ifmo/epampractice/dao/UsersDAOTest.java
  src/test/resources/Database_script_test.sql
  src/test/resources/Insert_test_script_H2.sql
Labels: invalid

#96 Issue #95 Add JSP pages and static files
  src/main/java/com/ifmo/epampractice/controllers/MainServlet.java
  src/main/java/com/ifmo/epampractice/controllers/UsersServlet.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/bootstrap/css/bootstrap.min.css
  src/main/webapp/assets/bootstrap/js/bootstrap.min.js
  src/main/webapp/assets/css/styles.min.css
  src/main/webapp/assets/fonts/FontAwesome.otf
  src/main/webapp/assets/fonts/font-awesome.min.css
  src/main/webapp/assets/fonts/fontawesome-webfont.eot
  src/main/webapp/assets/fonts/fontawesome-webfont.svg
  src/main/webapp/assets/fonts/fontawesome-webfont.ttf
  src/main/webapp/assets/fonts/fontawesome-webfont.woff
  src/main/webapp/assets/fonts/fontawesome-webfont.woff2
  src/main/webapp/assets/fonts/ionicons.eot
  src/main/webapp/assets/fonts/ionicons.min.css
  src/main/webapp/assets/fonts/ionicons.svg
  src/main/webapp/assets/fonts/ionicons.ttf
  src/main/webapp/assets/fonts/ionicons.woff
  src/main/webapp/assets/img/1.jpg
  src/main/webapp/assets/img/2.jpg
  src/main/webapp/assets/img/3.jpg
  src/main/webapp/assets/img/4.jpg
  src/main/webapp/assets/img/green-chameleon-s9CC2SKySJM-unsplash.jpg
  src/main/webapp/assets/img/meeting.jpg
  src/main/webapp/assets/img/person.png
  src/main/webapp/assets/img/screen-content-iphone-6.jpg
  src/main/webapp/assets/img/test (1).png
  src/main/webapp/assets/js/jquery.min.js
  src/main/webapp/auth/login.jsp
  src/main/webapp/auth/signin.jsp
  src/main/webapp/blocks/footer.jsp
  src/main/webapp/blocks/head.jsp
  src/main/webapp/groups/all.jsp
  src/main/webapp/groups/edit.jsp
  src/main/webapp/index.jsp
  src/main/webapp/profile/profile.jsp
  src/main/webapp/subjects/all.jsp
  src/main/webapp/subjects/edit.jsp
  src/main/webapp/tests/all.jsp
  src/main/webapp/tests/edit-answ.jsp
  src/main/webapp/tests/edit-quest.jsp
  src/main/webapp/tests/edit.jsp
  src/main/webapp/tests/test_group_all.jsp
  src/main/webapp/tests/test_group_edit.jsp
  src/main/webapp/users/all.jsp
  src/main/webapp/users/edit.jsp
Labels: enhancement

#97 Issue 73 service for subjects dao
  src/main/java/com/ifmo/epampractice/service/SubjectsService.java
Labels: enhancement

#89 Issue #74 Add UserService & SecurityUtilities & UsersDAO method
  src/main/java/com/ifmo/epampractice/dao/UsersDAO.java
  src/main/java/com/ifmo/epampractice/service/UsersService.java
  src/main/java/com/ifmo/epampractice/utilities/SecurityUtilities.java
Labels: enhancement
